CREATE TABLE customers (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(255),
    descr VARCHAR(255),
    age INT,
    course VARCHAR(255),
    password VARCHAR(255),
    dataCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    dataUpdated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    image_path VARCHAR(500) NULL
);
